import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  content: {
    padding: 20,
    paddingBottom: 42,
    gap: 16,
  },
  hero: {
    gap: 18,
    padding: 24,
    borderRadius: 36,
    borderCurve: "continuous",
    backgroundColor: "rgba(14,17,34,0.84)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.2)",
    boxShadow: "0 22px 64px rgba(0,0,0,0.32)",
    alignItems: "center",
  },
  heroTopStack: {
    width: "100%",
    alignItems: "center",
    gap: 12,
  },
  signalBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    alignSelf: "center",
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    backgroundColor: "rgba(247,211,139,0.12)",
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#F7D38B",
  },
  signalBadgeText: {
    color: "#F7D38B",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  settingsEntry: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  settingsEntryText: {
    color: "#F8F0DE",
    fontSize: 12,
    fontWeight: "800",
  },
  heroTitle: {
    color: "#F8F0DE",
    fontSize: 38,
    lineHeight: 41,
    fontWeight: "900",
    letterSpacing: -1.45,
    textAlign: "center",
  },
  heroCopy: {
    color: "#BFC6DE",
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
    maxWidth: 320,
  },
  heroPromiseRow: {
    flexDirection: "row",
    gap: 9,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  demoLockPill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    gap: 8,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "rgba(247,211,139,0.12)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.22)",
  },
  demoLockText: {
    color: "#F7D38B",
    fontSize: 12,
    fontWeight: "800",
  },
  miniPromise: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 8,
    backgroundColor: "rgba(255,255,255,0.07)",
  },
  miniPromiseText: {
    color: "#F8F0DE",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  heroStatsGrid: {
    flexDirection: "row",
    gap: 10,
  },
  heroStatCard: {
    flex: 1,
    gap: 8,
    padding: 14,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  heroStatLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  heroStatLabel: {
    color: "#AEB6D4",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  heroStatValue: {
    color: "#F8F0DE",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: -0.3,
  },
  transmissionShell: {
    position: "relative",
  },
  transmissionArrivalOverlay: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    borderRadius: 30,
    borderCurve: "continuous",
    backgroundColor: "rgba(8,10,23,0.68)",
    paddingHorizontal: 24,
  },
  transmissionArrivalSweep: {
    position: "absolute",
    width: 120,
    height: "150%",
    backgroundColor: "rgba(247,211,139,0.16)",
    borderRadius: 999,
  },
  transmissionArrivalGlow: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: "rgba(247,211,139,0.18)",
  },
  transmissionArrivalCore: {
    position: "absolute",
    width: 148,
    height: 148,
    borderRadius: 74,
    backgroundColor: "rgba(247,211,139,0.16)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.3)",
  },
  transmissionArrivalStars: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 2,
  },
  transmissionArrivalStar: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#F7D38B",
    shadowColor: "#F7D38B",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 8,
  },
  transmissionArrivalStarSmall: {
    width: 5,
    height: 5,
    borderRadius: 3,
    opacity: 0.8,
  },
  transmissionArrivalBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: "rgba(247,211,139,0.14)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.24)",
  },
  transmissionArrivalDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#F7D38B",
  },
  transmissionArrivalEyebrow: {
    color: "#F7D38B",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  transmissionArrivalTitle: {
    color: "#F8F0DE",
    fontSize: 28,
    lineHeight: 30,
    fontWeight: "900",
    letterSpacing: -0.8,
    textAlign: "center",
  },
  transmissionArrivalCopy: {
    maxWidth: 260,
    color: "#D6DCEF",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
    textAlign: "center",
  },
  receiveCard: {
    gap: 14,
    padding: 18,
    borderRadius: 30,
    borderCurve: "continuous",
    backgroundColor: "rgba(246,240,222,0.08)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.18)",
    alignItems: "center",
  },
  receiveHeader: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  receiveHeaderCopy: {
    flex: 1,
    gap: 5,
    alignItems: "center",
  },
  receiveIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(247,211,139,0.12)",
  },
  sectionTitle: {
    color: "#F8F0DE",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: -0.55,
    textAlign: "center",
  },
  sectionCopy: {
    color: "#AEB6D4",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  wordInput: {
    width: "100%",
    minHeight: 58,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.08)",
    color: "#F8F0DE",
    paddingHorizontal: 17,
    fontSize: 22,
    fontWeight: "900",
    textAlign: "center",
  },
  noteInput: {
    width: "100%",
    minHeight: 82,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.06)",
    color: "#F8F0DE",
    padding: 15,
    fontSize: 15,
    lineHeight: 21,
    textAlign: "center",
  },
  detailToggle: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    gap: 6,
    paddingVertical: 6,
  },
  detailToggleText: {
    color: "#F7D38B",
    fontSize: 13,
    fontWeight: "700",
  },
  detailWrap: {
    gap: 10,
    width: "100%",
  },
  nudgeWrap: {
    gap: 8,
    width: "100%",
    alignItems: "center",
  },
  nudgeLabel: {
    color: "#8F96B4",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 0.4,
    textTransform: "uppercase",
    textAlign: "center",
  },
  nudgeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "center",
  },
  nudgeChip: {
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 9,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  nudgeChipActive: {
    backgroundColor: "rgba(247,211,139,0.18)",
    borderColor: "rgba(247,211,139,0.45)",
  },
  nudgeText: {
    color: "#AEB6D4",
    fontSize: 12,
    fontWeight: "800",
  },
  nudgeTextActive: {
    color: "#F7D38B",
  },
  receiveButton: {
    minHeight: 56,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: "#F7D38B",
    alignItems: "center",
    justifyContent: "center",
  },
  receiveText: {
    color: "#101320",
    fontSize: 16,
    fontWeight: "900",
  },
  choiceCard: {
    gap: 12,
    padding: 18,
    borderRadius: 28,
    borderCurve: "continuous",
    backgroundColor: "rgba(14,17,34,0.72)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
  },
  threadTargetSection: {
    gap: 8,
    width: "100%",
    alignItems: "center",
  },
  threadTargetGrid: {
    gap: 10,
    width: "100%",
  },
  threadTargetChip: {
    gap: 5,
    padding: 12,
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  threadTargetChipActive: {
    backgroundColor: "rgba(247,211,139,0.14)",
    borderColor: "rgba(247,211,139,0.3)",
  },
  threadTargetEyebrow: {
    color: "#8F96B4",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    textAlign: "center",
  },
  threadTargetEyebrowActive: {
    color: "#F7D38B",
  },
  threadTargetTitle: {
    color: "#D7DCEE",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  threadTargetTitleActive: {
    color: "#F8F0DE",
  },
  choiceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "center",
  },
  choiceOutcomeCard: {
    gap: 8,
    padding: 14,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: "rgba(247,211,139,0.09)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.18)",
  },
  choiceOutcomeHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  choiceOutcomeTitle: {
    color: "#F8F0DE",
    fontSize: 15,
    fontWeight: "900",
  },
  choiceOutcomeBody: {
    color: "#D8DDF0",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  choiceOutcomeMeta: {
    color: "#F6DDA9",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  actionNudgeGrid: {
    gap: 8,
  },
  actionNudge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 12,
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: "rgba(247,211,139,0.1)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.16)",
  },
  actionNudgeText: {
    color: "#F6DDA9",
    fontSize: 13,
    fontWeight: "800",
  },
  choiceButton: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
  },
  choiceButtonActive: {
    backgroundColor: "rgba(247,211,139,0.18)",
    borderColor: "rgba(247,211,139,0.45)",
  },
  choiceText: {
    color: "#AEB6D4",
    fontWeight: "800",
  },
  choiceTextActive: {
    color: "#F7D38B",
  },
  unlockCard: {
    gap: 14,
    padding: 18,
    borderRadius: 28,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.055)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  unlockHeader: {
    gap: 5,
  },
  nextUnlockCard: {
    gap: 10,
    padding: 14,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: "rgba(247,211,139,0.1)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.18)",
  },
  nextUnlockHeader: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  nextUnlockBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#F7D38B",
    alignItems: "center",
    justifyContent: "center",
  },
  nextUnlockCopy: {
    flex: 1,
    gap: 4,
  },
  nextUnlockTitle: {
    color: "#F8F0DE",
    fontSize: 15,
    fontWeight: "900",
  },
  nextUnlockText: {
    color: "#D2D8EE",
    fontSize: 13,
    lineHeight: 18,
  },
  nextUnlockMood: {
    color: "#F7D38B",
    fontSize: 12,
    fontWeight: "800",
  },
  systemSignalsCard: {
    gap: 10,
    padding: 14,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.045)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  systemSignalsCardWarning: {
    borderColor: "rgba(255,154,154,0.2)",
    backgroundColor: "rgba(255,154,154,0.05)",
  },
  systemSignalsCardRare: {
    borderColor: "rgba(247,211,139,0.22)",
    backgroundColor: "rgba(247,211,139,0.06)",
  },
  systemSignalsEventCard: {
    gap: 5,
    padding: 12,
    borderRadius: 16,
    borderCurve: "continuous",
    backgroundColor: "rgba(14,17,34,0.42)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  systemSignalsEventTitle: {
    color: "#F8F0DE",
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "900",
  },
  systemSignalsEventBody: {
    color: "#D7DCEE",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  systemSignalsTitle: {
    color: "#F8F0DE",
    fontSize: 15,
    fontWeight: "900",
  },
  systemSignalsList: {
    gap: 10,
  },
  systemSignalItem: {
    gap: 4,
  },
  systemSignalEyebrow: {
    color: "#8F96B4",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  systemSignalHeading: {
    color: "#F6DDA9",
    fontSize: 13,
    lineHeight: 17,
    fontWeight: "800",
  },
  systemSignalBody: {
    color: "#D2D8EE",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  voiceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  voiceOrbWrap: {
    width: "30%",
    minWidth: 92,
    flexGrow: 1,
    alignItems: "center",
    gap: 7,
  },
  voiceOrb: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(247,211,139,0.11)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.18)",
  },
  voiceOrbUnlocked: {
    backgroundColor: "#F7D38B",
    borderColor: "#F7D38B",
  },
  voiceOrbQuiet: {
    backgroundColor: "rgba(247,211,139,0.08)",
    borderColor: "rgba(247,211,139,0.26)",
  },
  voiceLabel: {
    color: "#F8F0DE",
    fontSize: 11,
    lineHeight: 14,
    textAlign: "center",
    fontWeight: "800",
  },
  voiceHint: {
    color: "#8F96B4",
    fontSize: 10,
    lineHeight: 13,
    textAlign: "center",
    fontWeight: "700",
  },
  storyCard: {
    gap: 12,
    padding: 18,
    borderRadius: 28,
    borderCurve: "continuous",
    backgroundColor: "rgba(14,17,34,0.66)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  storyList: {
    gap: 10,
  },
  storyItem: {
    gap: 6,
    padding: 14,
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  storyEyebrow: {
    color: "#F7D38B",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  storyTitle: {
    color: "#F8F0DE",
    fontSize: 15,
    fontWeight: "900",
  },
  storyBody: {
    color: "#BFC6DE",
    fontSize: 13,
    lineHeight: 19,
  },
  memoryCard: {
    gap: 14,
    padding: 18,
    borderRadius: 28,
    borderCurve: "continuous",
    backgroundColor: "rgba(12,16,31,0.82)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.12)",
  },
  memoryHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  memoryHeaderRow: {
    gap: 12,
  },
  memoryBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(247,211,139,0.1)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.16)",
  },
  memoryCopy: {
    flex: 1,
    gap: 4,
  },
  memoryArchiveButton: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  memoryArchiveButtonText: {
    color: "#F7D38B",
    fontSize: 12,
    fontWeight: "900",
  },
  memorySummaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  memorySummaryPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    backgroundColor: "rgba(247,211,139,0.12)",
  },
  memorySummaryPillMuted: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  memorySummaryText: {
    color: "#F7D38B",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  memorySummaryTextMuted: {
    color: "#AEB6D4",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  memoryFilterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  memoryFilterChip: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 9,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  memoryFilterChipActive: {
    backgroundColor: "rgba(247,211,139,0.16)",
    borderColor: "rgba(247,211,139,0.34)",
  },
  memoryFilterText: {
    color: "#AEB6D4",
    fontSize: 12,
    fontWeight: "800",
  },
  memoryFilterTextActive: {
    color: "#F7D38B",
  },
  memoryEmptyState: {
    gap: 8,
    alignItems: "flex-start",
    padding: 16,
    borderRadius: 20,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  memoryEmptyTitle: {
    color: "#F8F0DE",
    fontSize: 14,
    fontWeight: "900",
  },
  memoryEmptyBody: {
    color: "#AEB6D4",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  memoryList: {
    gap: 10,
  },
  memoryItem: {
    gap: 6,
    padding: 14,
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.045)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  memoryItemExpanded: {
    backgroundColor: "rgba(247,211,139,0.08)",
    borderColor: "rgba(247,211,139,0.16)",
  },
  memoryItemPinned: {
    borderColor: "rgba(247,211,139,0.22)",
    backgroundColor: "rgba(247,211,139,0.06)",
  },
  memoryMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  memoryLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  memoryMetaRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  memoryIndex: {
    color: "#F7D38B",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.9,
    textTransform: "uppercase",
  },
  memoryDate: {
    color: "#8F96B4",
    fontSize: 11,
    fontWeight: "700",
  },
  memoryPinnedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: "#F7D38B",
  },
  memoryPinnedBadgeText: {
    color: "#101320",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  memoryVoice: {
    color: "#D7DCEE",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  memoryTitle: {
    color: "#F8F0DE",
    fontSize: 15,
    lineHeight: 19,
    fontWeight: "900",
  },
  memoryTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  memoryTitleCopy: {
    flex: 1,
    gap: 4,
  },
  memoryPinButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(247,211,139,0.08)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.16)",
  },
  memoryPinButtonPinned: {
    backgroundColor: "#F7D38B",
    borderColor: "#F7D38B",
  },
  memoryPressArea: {
    gap: 6,
  },
  memoryBody: {
    color: "#BFC6DE",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  memoryExpandHint: {
    color: "#8F96B4",
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
  },
  memoryExpandedContent: {
    gap: 10,
    marginTop: 2,
    paddingTop: 10,
    borderTopWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  memoryExcerpt: {
    color: "#D7DCEE",
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "700",
  },
  memoryActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  memoryAction: {
    flex: 1,
    color: "#F7D38B",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "800",
  },
  memoryArchiveEntryRow: {
    gap: 12,
    padding: 18,
    borderRadius: 24,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  memoryArchiveEntryCopy: {
    color: "#D7DCEE",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  memoryArchiveEntryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-start",
    gap: 8,
    minHeight: 42,
    borderRadius: 999,
    paddingHorizontal: 14,
    backgroundColor: "#F7D38B",
  },
  memoryArchiveEntryButtonText: {
    color: "#101320",
    fontSize: 13,
    fontWeight: "900",
  },
  archiveScreenContent: {
    padding: 20,
    paddingTop: 120,
    paddingBottom: 42,
    gap: 18,
  },
  archiveHero: {
    gap: 14,
    padding: 22,
    borderRadius: 30,
    borderCurve: "continuous",
    backgroundColor: "rgba(14,17,34,0.82)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.16)",
  },
  archiveEyebrow: {
    color: "#F7D38B",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  archiveTitle: {
    color: "#F8F0DE",
    fontSize: 30,
    lineHeight: 32,
    fontWeight: "900",
    letterSpacing: -0.9,
  },
  archiveBody: {
    color: "#BFC6DE",
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "700",
  },
  archiveStatsRow: {
    flexDirection: "row",
    gap: 10,
  },
  archiveStatCard: {
    flex: 1,
    gap: 5,
    padding: 14,
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  archiveStatValue: {
    color: "#F8F0DE",
    fontSize: 22,
    fontWeight: "900",
    fontVariant: ["tabular-nums"],
  },
  archiveStatLabel: {
    color: "#AEB6D4",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  archiveLoadingState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  archiveLoadingText: {
    color: "#BFC6DE",
    fontSize: 15,
    fontWeight: "700",
  },
  refinementCard: {
    gap: 14,
    padding: 18,
    borderRadius: 24,
    borderCurve: "continuous",
    backgroundColor: "rgba(247,211,139,0.08)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.18)",
  },
  refinementHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  refinementBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(247,211,139,0.12)",
  },
  refinementCopy: {
    flex: 1,
    gap: 4,
    alignItems: "center",
  },
  refinementTitle: {
    color: "#F8F0DE",
    fontSize: 15,
    fontWeight: "900",
    textAlign: "center",
  },
  refinementBody: {
    color: "#D7DCEE",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
    textAlign: "center",
  },
  refinementButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minHeight: 48,
    borderRadius: 16,
    backgroundColor: "#F7D38B",
  },
  refinementButtonText: {
    color: "#101320",
    fontSize: 14,
    fontWeight: "900",
  },
  contextNote: {
    flexDirection: "row",
    gap: 9,
    alignItems: "flex-start",
    padding: 12,
    borderRadius: 18,
    borderCurve: "continuous",
    backgroundColor: "rgba(255,255,255,0.055)",
  },
  contextNoteText: {
    flex: 1,
    color: "#AEB6D4",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "700",
  },
  footnote: {
    color: "#8F96B4",
    fontSize: 12,
    textAlign: "center",
  },
  error: {
    color: "#FF9A9A",
    fontSize: 13,
    lineHeight: 18,
  },
  pressed: {
    opacity: 0.78,
    transform: [{ scale: 0.99 }],
  },
  flareGlow: {
    position: "absolute",
    top: -50,
    left: -50,
    right: -50,
    bottom: -50,
    borderWidth: 40,
    borderRadius: 999,
    opacity: 0.3,
  },
  shareRow: {
    alignItems: "center",
    paddingVertical: 4,
  },
  shareButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "rgba(247,211,139,0.08)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.18)",
  },
  shareButtonText: {
    color: "#F7D38B",
    fontSize: 13,
    fontWeight: "700",
  },
  milestoneOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1000,
    justifyContent: "center",
    alignItems: "center",
  },
  milestoneBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(8,10,23,0.85)",
  },
  milestoneCard: {
    width: 300,
    padding: 32,
    borderRadius: 28,
    borderCurve: "continuous",
    backgroundColor: "rgba(14,17,34,0.96)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.22)",
    alignItems: "center",
    gap: 14,
    zIndex: 1,
  },
  milestoneEmoji: {
    fontSize: 48,
  },
  milestoneTitle: {
    color: "#F7D38B",
    fontSize: 24,
    fontWeight: "900",
    letterSpacing: -0.5,
  },
  milestoneCopy: {
    color: "#BFC6DE",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  milestoneActions: {
    gap: 10,
    width: "100%",
    marginTop: 6,
  },
  milestoneShareButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 13,
    borderRadius: 16,
    backgroundColor: "#F7D38B",
  },
  milestoneShareText: {
    color: "#101320",
    fontSize: 14,
    fontWeight: "800",
  },
  milestoneDismiss: {
    alignItems: "center",
    paddingVertical: 10,
  },
  milestoneDismissText: {
    color: "#8F96B4",
    fontSize: 13,
    fontWeight: "700",
  },
});
