import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  gradientBg: {
    flex: 1,
  },
  // ─── Locked state ───
  lockedScroll: {
    padding: 24,
    paddingTop: 80,
    paddingBottom: 60,
    alignItems: "center",
    gap: 16,
  },
  lockedIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(247,211,139,0.08)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.16)",
    marginBottom: 8,
  },
  lockedTitle: {
    color: "#F8F0DE",
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: -0.6,
    textAlign: "center",
  },
  lockedSubtitle: {
    color: "#AEB6D4",
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    maxWidth: 300,
  },
  milestoneCard: {
    gap: 10,
    padding: 20,
    borderRadius: 24,
    backgroundColor: "rgba(14,17,34,0.72)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.16)",
    width: "100%",
    maxWidth: 400,
  },
  milestoneHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  milestoneLabel: {
    color: "#F7D38B",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
  },
  progressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#F7D38B",
    borderRadius: 3,
  },
  milestoneHint: {
    color: "#8F96B4",
    fontSize: 12,
    textAlign: "center",
    fontWeight: "600",
  },
  previewList: {
    gap: 14,
    width: "100%",
    maxWidth: 400,
  },
  previewTitle: {
    color: "#F8F0DE",
    fontSize: 16,
    fontWeight: "900",
  },
  previewItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  previewIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(247,211,139,0.1)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.16)",
  },
  previewText: {
    flex: 1,
    color: "#BFC6DE",
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "600",
  },
  // ─── Unlocked state ───
  unlockedScroll: {
    padding: 24,
    paddingTop: 80,
    paddingBottom: 60,
    gap: 16,
  },
  unlockedHeader: {
    alignItems: "center",
    gap: 10,
  },
  unlockedIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(247,211,139,0.1)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.2)",
  },
  unlockedTitle: {
    color: "#F8F0DE",
    fontSize: 28,
    fontWeight: "900",
    letterSpacing: -0.6,
    textAlign: "center",
  },
  unlockedSubtitle: {
    color: "#AEB6D4",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
    maxWidth: 300,
  },
  creditsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  creditsText: {
    color: "#BFC6DE",
    fontSize: 14,
    fontWeight: "700",
  },
  premiumBadge: {
    backgroundColor: "rgba(179,136,255,0.18)",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: "rgba(179,136,255,0.3)",
  },
  premiumBadgeText: {
    color: "#B388FF",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
  },
  inputContainer: {
    gap: 16,
  },
  modeToggle: {
    flexDirection: "row",
    gap: 8,
  },
  modeButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  modeButtonActive: {
    borderColor: "rgba(247,211,139,0.35)",
    backgroundColor: "rgba(247,211,139,0.1)",
  },
  modeButtonText: {
    color: "#8F96B4",
    fontSize: 13,
    fontWeight: "800",
  },
  modeButtonTextActive: {
    color: "#F7D38B",
  },
  input: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 18,
    padding: 16,
    color: "#F8F0DE",
    fontSize: 16,
    minHeight: 100,
    textAlignVertical: "top",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  contextSummary: {
    gap: 10,
    padding: 16,
    borderRadius: 20,
    backgroundColor: "rgba(247,211,139,0.06)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.12)",
  },
  contextHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  contextTitle: {
    color: "#F8F0DE",
    fontSize: 14,
    fontWeight: "900",
  },
  contextItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  contextItemText: {
    color: "#BFC6DE",
    fontSize: 13,
    fontWeight: "600",
  },
  generateButton: {
    borderRadius: 18,
    overflow: "hidden",
  },
  unlockNowButton: {
    borderRadius: 18,
    overflow: "hidden",
    width: "100%",
    maxWidth: 400,
  },
  awakenedSubtext: {
    color: "#8F96B4",
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
    maxWidth: 320,
    marginTop: -4,
  },
  buttonDisabled: {
    opacity: 0.4,
  },
  gradient: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 16,
    borderRadius: 18,
  },
  buttonText: {
    color: "#101320",
    fontSize: 16,
    fontWeight: "900",
  },
  // ─── Agent pipeline ───
  pipelineContainer: {
    gap: 16,
    padding: 20,
    borderRadius: 24,
    backgroundColor: "rgba(14,17,34,0.82)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.16)",
  },
  pipelineHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pipelineTitle: {
    color: "#F8F0DE",
    fontSize: 16,
    fontWeight: "900",
  },
  pipelineSteps: {
    gap: 10,
  },
  pipelineStep: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 10,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  pipelineStepActive: {
    backgroundColor: "rgba(247,211,139,0.08)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.2)",
  },
  pipelineStepComplete: {
    opacity: 0.6,
  },
  pipelineIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  pipelineIconWrapActive: {
    backgroundColor: "rgba(247,211,139,0.15)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.3)",
  },
  pipelineIconWrapComplete: {
    backgroundColor: "rgba(169,247,181,0.1)",
  },
  pipelineLabel: {
    color: "#6F7591",
    fontSize: 13,
    fontWeight: "700",
  },
  pipelineLabelActive: {
    color: "#F8F0DE",
  },
  pipelineLabelComplete: {
    color: "#A9F7B5",
  },
  pipelineProgressTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
  },
  pipelineProgressFill: {
    height: "100%",
    backgroundColor: "#F7D38B",
    borderRadius: 2,
  },
  // ─── Result ───
  resultScroll: {
    padding: 24,
    paddingTop: 80,
    paddingBottom: 60,
  },
  resultCard: {
    gap: 20,
    padding: 24,
    borderRadius: 28,
    backgroundColor: "rgba(14,17,34,0.84)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.16)",
    alignItems: "center",
  },
  emotionalCore: {
    fontSize: 18,
    fontWeight: "900",
    color: "#F7D38B",
    fontStyle: "italic",
    textAlign: "center",
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  audioPlayer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    width: "100%",
    padding: 16,
    borderRadius: 20,
    backgroundColor: "rgba(9,11,24,0.5)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  audioPlayButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F7D38B",
  },
  audioPlayerInfo: {
    flex: 1,
    gap: 3,
  },
  audioLabel: {
    color: "#F8F0DE",
    fontSize: 14,
    fontWeight: "800",
  },
  audioSubtext: {
    color: "#8F96B4",
    fontSize: 11,
    fontWeight: "600",
  },
  transcript: {
    fontSize: 20,
    lineHeight: 30,
    color: "#E8E1D3",
    fontFamily: Platform.OS === "ios" ? "Georgia" : "serif",
    textAlign: "center",
    fontStyle: "italic",
  },
  mediaPlaceholder: {
    width: "100%",
    aspectRatio: 16 / 9,
    backgroundColor: "#000",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  playButtonOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  critiqueBox: {
    width: "100%",
    gap: 8,
    padding: 16,
    borderRadius: 16,
    backgroundColor: "rgba(247,211,139,0.06)",
    borderWidth: 1,
    borderColor: "rgba(247,211,139,0.12)",
  },
  critiqueHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  critiqueTitle: {
    color: "#F7D38B",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  critiqueText: {
    color: "#BFC6DE",
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "600",
  },
  tierBadgeWrap: {
    alignItems: "center",
  },
  tierBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  tierBadgePremium: {
    backgroundColor: "rgba(179,136,255,0.12)",
    borderColor: "rgba(179,136,255,0.25)",
  },
  tierBadgeText: {
    color: "#8F96B4",
    fontSize: 11,
    fontWeight: "800",
  },
  tierBadgeTextPremium: {
    color: "#B388FF",
  },
  shareButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
    padding: 16,
    borderRadius: 18,
    backgroundColor: "#F7D38B",
  },
  shareButtonText: {
    color: "#101320",
    fontSize: 16,
    fontWeight: "900",
  },
  resetButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: 12,
  },
  resetButtonText: {
    color: "#8F96B4",
    fontSize: 14,
    fontWeight: "700",
  },
  errorText: {
    color: "#FF9A9A",
    textAlign: "center",
    marginTop: 20,
    fontSize: 14,
    fontWeight: "600",
  },
  pressed: {
    opacity: 0.78,
    transform: [{ scale: 0.98 }],
  },
});
