import { v } from "convex/values";
import { action, mutation, query } from "./_generated/server";
import { getAuthUserId } from "@convex-dev/auth/server";
import { generateWithAI } from "./ai";

export const getSyntheses = query({
  args: {},
  handler: async (ctx) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) return null;

    return await ctx.db
      .query("syntheses")
      .withIndex("by_userId", (q) => q.eq("userId", userId))
      .order("desc")
      .collect();
  },
});

export const saveSynthesis = mutation({
  args: {
    weekStartDateKey: v.string(),
    summary: v.string(),
    actionItems: v.array(v.string()),
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Unauthorized");

    const existing = await ctx.db
      .query("syntheses")
      .withIndex("by_userId_and_week", (q) =>
        q.eq("userId", userId).eq("weekStartDateKey", args.weekStartDateKey),
      )
      .first();

    if (existing) {
      return existing._id;
    }

    return await ctx.db.insert("syntheses", {
      userId,
      weekStartDateKey: args.weekStartDateKey,
      summary: args.summary,
      actionItems: args.actionItems,
      createdAt: Date.now(),
    });
  },
});

export const generateWeeklySynthesis = action({
  args: {
    dateKey: v.string(), // Today's dateKey
    weekStartDateKey: v.string(), // Start dateKey of the 7 days
    transmissionsText: v.string(), // Pre-formatted text of the week's log
  },
  handler: async (ctx, args) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Unauthorized");

    const systemPrompt = `You are a deeply empathetic, psychological synthesis AI for the 'Future Selves' platform.
The user has spent the last 7 days checking in, receiving messages from their 'future selves' (archetypes), and reflecting on them.
Your job is to read their 7-day log and synthesize it into a coherent, actionable review.

Output EXACTLY AND ONLY a valid JSON object with two fields:
{
  "summary": "A 2-3 sentence deeply resonant summary of their week's psychological throughline. Speak directly to them (e.g. 'This week, you wrestled with...').",
  "actionItems": [
    "A highly specific, concrete, real-world action they can take next week based on their reflections (max 15 words).",
    "Another specific action..."
  ]
}
Provide exactly 2 to 3 actionItems. Do not wrap the JSON in markdown code blocks, output only the JSON object itself.`;

    const userPrompt = `Here is the user's 7-day log:\n\n${args.transmissionsText}\n\nPlease generate the synthesis.`;

    const responseText = await generateWithAI(userPrompt, systemPrompt);
    if (!responseText) {
      throw new Error("AI failed to generate synthesis.");
    }

    try {
      // Strip potential markdown backticks
      const cleanJson = responseText.replace(/^```json/i, "").replace(/^```/i, "").replace(/```$/i, "").trim();
      const result = JSON.parse(cleanJson);
      
      if (!result.summary || !Array.isArray(result.actionItems)) {
        throw new Error("Invalid schema from AI");
      }

      await ctx.runMutation((await import("./synthesis")).saveSynthesis, {
        weekStartDateKey: args.weekStartDateKey,
        summary: result.summary,
        actionItems: result.actionItems,
      });

      return { success: true };
    } catch (e) {
      console.error("Failed to parse synthesis JSON:", responseText, e);
      throw new Error("Failed to parse the synthesis generated by AI.");
    }
  },
});
